apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/hekonsek/demo-e2ee333444:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/hekonsek/demo-e2ee333444:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: demo-e2ee333444
        chartPath: charts/demo-e2ee333444
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/hekonsek/demo-e2ee333444"
          image.tag: "{{.TAG}}"
